services:
  mysql:
    container_name: mysql
    image: mysql:8
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: restdb
      MYSQL_USER: restadmin
      MYSQL_PASSWORD: password
    expose:
     - "3306"
  mongo:
    container_name: mongo
    image: mongo
    platform: linux/arm64
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    expose:
      - "27017"
  auth-server:
    container_name: auth-server
    image: spring-6-auth-server:0.0.1-SNAPSHOT
    platform: linux/amd64
    expose:
      - 9000
  rest-mvc:
    container_name: rest-mvc
    image: spring-6-rest-mvc:0.0.1-SNAPSHOT
    platform: linux/amd64
    expose:
      - 8080
    environment:
      - SPRING_PROFILES_ACTIVE=localmysql
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://auth-server:9000
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/restdb    
      - SERVER_PORT=8080
    depends_on:
      - mysql
  reactive:
    container_name: reactive
    image: spring-6-reactive:0.0.1-SNAPSHOT
    platform: linux/amd64
    expose:
     - 8080
    environment:
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://auth-server:9000
  reactive-mongo:
    container_name: reactive-mongo
    image: reactive-mongo:0.0.1-SNAPSHOT
    platform: linux/amd64
    expose:
      - 8080
    environment:
      - SERVER_PORT=8080
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://auth-server:9000
      - SFG_MONGOHOST=mongo
    depends_on:
      - mongo
  gateway:
    container_name: gateway
    image: spring-6-gateway:0.0.1-SNAPSHOT
    platform: linux/amd64
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://auth-server:9000
    depends_on:
      - auth-server
      - rest-mvc
      - reactive
      - reactive-mongo      





































